title: Tarighabio Soun-Uche Data Analytics Portfolio
logo: Data Analytics B.jpg
description: A Data Analyst with 2 years experience analysing data using tools such SQL, Excel, and Power BI
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
