title: Tarighabio Soun-Uche Data Analytics Portfolio
logo: Data Analytics B.jpg
description: Result-driven data analyst with 2+ years of experience using Excel, Power BI, and SQL to drive business insights and iinformed decision-making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
